In [3]:
import pandas as pd

In [4]:
csv_url = "https://raw.githubusercontent.com/yaojenkuo/ml-newbies/master/player_stats.csv"
player_stats = pd.read_csv(csv_url)
print(type(player_stats))
print(player_stats.shape)


<class 'pandas.core.frame.DataFrame'>
(503, 50)


In [5]:
player_stats

firstName          lastName       temporaryDisplayName  personId  \
0    Precious           Achiuwa          Achiuwa, Precious   1630173   
1      Steven             Adams              Adams, Steven    203500   
2         Bam           Adebayo               Adebayo, Bam   1628389   
3     Ty-Shon         Alexander         Alexander, Ty-Shon   1630234   
4     Nickeil  Alexander-Walker  Alexander-Walker, Nickeil   1629638   
..        ...               ...                        ...       ...   
498  Thaddeus             Young            Young, Thaddeus    201152   
499      Trae             Young                Young, Trae   1629027   
500      Omer         Yurtseven            Yurtseven, Omer   1630209   
501      Cody            Zeller               Zeller, Cody    203469   
502     Ivica             Zubac               Zubac, Ivica   1627826   

         teamId  jersey  isActive  pos  heightFeet  heightInches  ...     ftm  \
0    1610612748     5.0      True    F           6             8  ...    56.0   
1    1610612740    12.0      True    C           6            11  ...   936.0   
2    1610612748    13.0      True  C-F           6             9  ...   842.0   
3    1610612756     0.0      True    G           6             3  ...     1.0   
4    1610612740     6.0      True    G           6             6  ...    73.0   
..          ...     ...       ...  ...         ...           ...  ...     ...   
498  1610612741    21.0      True    F           6             8  ...  1370.0   
499  1610612737    11.0      True    G           6             1  ...  1308.0   
500  1610612748    77.0      True    C           7             0  ...     NaN   
501  1610612766    40.0      True  F-C           6            11  ...   960.0   
502  1610612746    40.0      True    C           7             0  ...   431.0   

        fta  pFouls   points  gamesPlayed  gamesStarted plusMinus      min  \
0     110.0    91.0    304.0         61.0           4.0    -116.0    737.0   
1    1708.0  1497.0   5629.0        588.0         524.0    1638.0  15812.0   
2    1141.0   668.0   3549.0        287.0         183.0     258.0   7840.0   
3       2.0     2.0      9.0         15.0           0.0      -8.0     47.0   
4     103.0   145.0    775.0         93.0          14.0    -105.0   1597.0   
..      ...     ...      ...          ...           ...       ...      ...   
498  2053.0  2268.0  13526.0       1033.0         710.0    -157.0  30932.0   
499  1519.0   355.0   4921.0        204.0         204.0    -295.0   6748.0   
500     NaN     NaN      NaN          NaN           NaN       NaN      NaN   
501  1316.0  1225.0   4062.0        467.0         273.0     196.0  10618.0   
502   563.0   605.0   2216.0        284.0         151.0     357.0   4992.0   

       dd2  td3  
0      3.0  0.0  
1    125.0  1.0  
2     91.0  5.0  
3      0.0  0.0  
4      0.0  0.0  
..     ...  ...  
498  109.0  0.0  
499   86.0  3.0  
500    NaN  NaN  
501   37.0  0.0  
502   36.0  0.0  

[503 rows x 50 columns]

In [7]:
player_stats.keys()

Index(['firstName', 'lastName', 'temporaryDisplayName', 'personId', 'teamId',
       'jersey', 'isActive', 'pos', 'heightFeet', 'heightInches',
       'heightMeters', 'weightPounds', 'weightKilograms', 'dateOfBirthUTC',
       'nbaDebutYear', 'yearsPro', 'collegeName', 'lastAffiliation', 'country',
       'isallStar', 'tpp', 'ftp', 'fgp', 'ppg', 'rpg', 'apg', 'bpg', 'mpg',
       'spg', 'assists', 'blocks', 'steals', 'turnovers', 'offReb', 'defReb',
       'totReb', 'fgm', 'fga', 'tpm', 'tpa', 'ftm', 'fta', 'pFouls', 'points',
       'gamesPlayed', 'gamesStarted', 'plusMinus', 'min', 'dd2', 'td3'],
      dtype='object')

In [14]:
X = player_stats[['apg', 'rpg']].values
Y = player_stats['pos'].values
print(X.shape)
print(Y.shape)

(503, 2)
(503,)


In [16]:
X = player_stats[['weightKilograms']].values
Y = player_stats['heightMeters'].values
#print(X)
#print(Y)

In [20]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression, Ridge

In [21]:
pf = PolynomialFeatures()
ss = StandardScaler()

lr = LinearRegression()
ridge = Ridge()

In [22]:
lr.fit(X, Y)

LinearRegression()

In [25]:
y_pred = lr.predict(X[0:1])
print(X[0:1])
print(Y[0], y_pred)

[[102.1]]
2.03 [2.01038663]


In [29]:
from sklearn.model_selection import train_test_split

In [30]:
from xgboost import XGBClassifier

In [31]:
X = player_stats[['heightMeters', 'apg', 'rpg']].values
y = player_stats['weightKilograms'].values

In [36]:
pos_dict = {
    'G': 0,
    'F': 1,
    'C': 2
}
pos_recoded = player_stats['pos'].map(lambda x: x[0])
pos_recoded_int = pos_recoded.map(pos_dict)
X = player_stats[['heightMeters', 'apg', 'rpg']].values
y = pos_recoded_int.values
print(X.shape)
print(y.shape)

(503, 3)
(503,)


In [37]:
X = player_stats[['heightMeters', 'apg', 'rpg']].values
y = pos_recoded_int.values
print(X.shape)
print(y.shape)

(503, 3)
(503,)


In [39]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(402, 3)
(101, 3)
(402,)
(101,)


In [40]:
xgb_c = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_c.fit(X_train, y_train)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eval_metric='mlogloss',
              gamma=0, gpu_id=-1, importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [42]:
from sklearn.metrics import accuracy_score
y_pred = xgb_c.predict(X_valid)
print(accuracy_score(y_valid, y_pred))


0.8811881188118812


In [1]:
import numpy as np

In [2]:
X0 = np.ones((10, 1))
X1 = np.arange(1, 11).reshape(-1, 1)
w = np.array([5, 6])
X_train = np.concatenate([X0, X1], axis=1)
y_train = np.dot(X_train, w)
print(X_train) # (10, 2) dot (2,)
print(y_train) # (10,)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]]
[11. 17. 23. 29. 35. 41. 47. 53. 59. 65.]


In [3]:
n = X_train.shape[1]
w = np.random.rand(2)
w

array([0.8418736 , 0.26889344])

In [10]:
n = X_train.shape[1]
w = np.random.rand(2)
y_hat = np.dot(X_train, w)
m = y_train.size
j = ((y_hat - y_train).T.dot(y_hat - y_train)) / m
print(w)
print(j)

[0.45495171 0.34419288]
1534.9664813179493


In [11]:
gradient = (2 / m) * X_train.T.dot(y_hat - y_train)
gradient

array([ -71.30397491, -485.49267946])

In [12]:
learning_rate = 0.0001
learning_rate * gradient

array([-0.0071304 , -0.04854927])

In [24]:
learning_rate = 0.0001
for i in range(100000):
    y_hat = np.dot(X_train, w)
    m = y_train.size
    j = ((y_hat - y_train).T.dot(y_hat - y_train)) / m
    gradient = (2 / m) * X_train.T.dot(y_hat - y_train)
    w -= learning_rate * gradient
print(w)

[4.98569025 6.00205546]


In [25]:
y_hat = np.dot(X_train, w)
print(y_hat)
print(y_train)

[10.98774571 16.98980117 22.99185663 28.99391209 34.99596755 40.99802301
 47.00007847 53.00213393 59.00418939 65.00624486]
[11. 17. 23. 29. 35. 41. 47. 53. 59. 65.]


In [26]:
w

array([4.98569025, 6.00205546])